# This is a basic workflow to help you get started with Actions

name: GitHub-Actions-Test

permissions:
  id-token: write
  contents: read

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'AZ CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Bicep file'
        run: az deployment group create --resource-group dev-personal-cv-website-backend --template-file main.bicep --parameters tableName=website_visitor_count primaryRegion=uksouth secondaryRegion=ukwest

      - name: 'List GitHub Workspace'
        run: ls $GITHUB_WORKSPACE