# This is a basic workflow to help you get started with Actions

name: Test

permissions:
  id-token: write
  contents: read

# Controls when the workflow will run
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - dev

env:
  RESOURCE_GROUP: personal-cv-website-backend
  COSMOS_TABLE_NAME: website_visitor_count
  FUNCTION_WORKER_RUNTIME: node
  FUNCTION_LANGUAGE: --javascript
  PRIMARY_DEPLOYMENT_REGION: uksouth
  SECONDARY_DEPLOYMENT_REGION: ukwest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Define variables'
        shell: bash
        run: |
          echo "Github.ref: ${{ github.ref }}"
          echo "Github.base_ref: ${{ github.base_ref }}"
          echo "Github.head_ref: ${{ github.head_ref }}"

          if [ "main" == "main" ]; then 
            echo "ENVIRONMENT=prod" >> "$GITHUB_ENV"
          elif [ "dev" == "dev" ]; then 
            echo "ENVIRONMENT=dev" >> "$GITHUB_ENV"
          fi

      - name: 'Test'
        run: echo "${{ env.ENVIRONMENT }}"